services:
  mongo-beer:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_beer_data:/data/db

  mysql-bar:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_bar_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-event:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_event_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  beer-service:
    depends_on:
      - mongo-beer
    image: iliaslatifine/beer-service
    ports:
      - 8080:8080
    links:
      - mongo-beer
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-beer

  bar-service:
    depends_on:
      - beer-service
      - mysql-bar
    image: iliaslatifine/bar-service
    ports:
      - 8081:8081
    links:
      - mysql-bar
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-bar
      MYSQL_DB_PORT: 3306
      BEER_SERVICE_BASERURL: beer-service:8080

  event-service:
    depends_on:
      - mysql-event
      - bar-service
    image: iliaslatifine/event-service
    ports:
      - 8082:8082
    links:
      - mysql-event
      - bar-service
    environment:
      BAR_SERVICE_BASEURL: product-service:8081
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-order
      MYSQL_DB_PORT: 3307

volumes:
  mongodb_beer_data:
  mysql_bar_data:
  mysql_event_data: