server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: beer-service-all
          uri: http://${BEER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/beers
            - Method=GET
          filters:
            - SetPath=/api/beer/all
        - id: beer-service-beers
          uri: http://${BEER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/beerlist
            - Method=GET
          filters:
            - SetPath=/api/beer