server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: beer-service-all
          uri: http://${BEER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/beers
            - Method=GET
          filters:
            - SetPath=/api/beer/all

        - id: beer-service-beers
          uri: http://${BEER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/beerlist
            - Method=GET
          filters:
            - SetPath=/api/beer

        - id: beer-service-post
          uri: http://${BEER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/beers
            - Method=POST
          filters:
            - SetPath=/api/beer

        - id: beer-service-delete
          uri: http://${BEER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/beers/{beerId}
            - Method=DELETE
          filters:
            - SetPath=/api/beer/{beerId}

        - id: bar-service-all
          uri: http://${BAR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bars
            - Method=GET
          filters:
            - SetPath=/api/bar/all

        - id: bar-service-bar
          uri: http://${BAR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bar
            - Method=GET
          filters:
            - SetPath=/api/bar

        - id: bar-service-post
          uri: http://${BAR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bars
            - Method=POST
          filters:
            - SetPath=/api/bar

        - id: bar-service-put
          uri: http://${BAR_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bars/{id}
            - Method=PUT
          filters:
            - SetPath=/api/bar/{id}

        - id: event-service-all
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/events
            - Method=GET
          filters:
            - SetPath=/api/event

        - id: event-service-post
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/events
            - Method=POST
          filters:
            - SetPath=/api/event

